### ISSUE TITLE
Better than the official, but of course be. UWP

### ISSUE THREAD

**Issue by bocanadamas** [CamSoper/WhosDown#6] opened 2016-01-22 11:17 UTC
It might someday be UWP, also operate in windows phone.

Suggestion:

 This could include a safety pin to open the app

**Comment by sebagomez** [comment] 2016-01-22 13:40
This app is an UWP app, but as stated, it's a wrap over the web.whatsapp site. Which, since is does not look responsive, the app does not look good in the phone.
Anyways, why would you want it on your phone when you can get the official WhatsApp app?

**Comment by bocanadamas** [comment] 2016-01-22 14:18
Due to the lack of updating of the official application and without the design of windows 10 update, I see this app (WhosDows), great potential to succeed in the mobile.

**Comment by CamSoper** [comment] 2016-01-22 16:30
Duplicate of #4

**Closed by CamSoper** 2016-01-22 16:30 UTC
Labels: duplicate
